### PR TITLE
Update messages.json

### PR DESCRIPTION
**Pull request by cyanotyp**
additional translations and typo fixes

### CODE REVIEW

**Comment by ysard** [comment]
Hi, thank you for your participation ;)

**Comment by cyanotyp** [comment]
Hi, no problem.
Do you need more translations ? as per the remark I could not 100% figure out if there is still some text missing (its my first contribution on github btw.)

**Comment by ysard** [comment]
No problem, and yes there is still text to translate;
Some strings are not translated in [messages.json](src/_locales/de/messages.json).
In a general way, all entries in the JSON file [messages.json](src/_locales/en/messages.json) that are not in the German version must be added to it ^^

**Comment by cyanotyp** [comment]
done, see my next pull request :)

**Pull request merged**
