### PR TITLE
Add German local

### PR DESCRIPTION
**Pull request by scheinercc**
Additional changes:
- [en] change “remove” to “delete” for consistency
- [en/fr] change to generic add-on URL without language

### CODE REVIEW

**Comment by ysard** [comment]
Hi, thank you very much for your participation to the project! It's motivating!
I am going to merge your pull request but before, could you include a short description written in German following the [templates of the displayed texts on AMO](cookie-quick-manager/tree/master/AMO/description)?

**Comment by scheinercc** [comment]
@ysard have a look

**Comment by ysard** [comment]
Thank you, it is done :)

**Comment by scheinercc** [comment]
Cool :)

**Pull request merged**
